# TODO: Use Case for Deployment on Portainer
#       - docker stack deploy (Docker Swarm)
#       - docker compose up (Docker Compose)

# Can update later for more deployment puposes


services:
  tools:
    image: ghcr.io/smkdev-id/smkdev-tools:latest
    container_name: smkdev-tools-app
    volumes:
      - app:/var/www/html
    ports:
      - "8000:80" # Expose Apache on port 8080 of the host
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel-network

volumes:
  app:

networks:
  laravel-network:
    driver: bridge