name: Build and Deploy Docker Image

# TODO: WE can use commit id for image tag on ghcr.io
# TODO: remove .env inside docker image, can be attach later

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Set up environment file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Set version number
        run: echo ${{ github.sha }} > version
      
      - run: cp deployment/Dockerfile.main ./Dockerfile
      - name: Build Docker image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository }}:latest \
          -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}